@startuml
hide empty members


interface DatabaseAPI #lightgreen


interface GUI #lightsalmon
GUI ..u..> ApplicationAPI


interface RecipeInterface #lightblue
interface ShoppingListInterface #lightblue
abstract class AbstractItem #lightblue

abstract class AbstractDatabaseAdapter #lightblue
AbstractDatabaseAdapter .u.> DatabaseAPI

class ConcreteDatabaseAdapter #lightblue
ConcreteDatabaseAdapter -l-|> AbstractDatabaseAdapter

class DataFlowController #lightblue
DataFlowController "1" .u.> "1..*" AbstractDatabaseAdapter

interface ApplicationAPI #lightblue
ApplicationAPI .u.|> RecipeInterface
ApplicationAPI .u.|> ShoppingListInterface

abstract class AbstractRecipe #lightblue
AbstractRecipe ..|> RecipeInterface

abstract class AbstractShoppingList #lightblue
AbstractShoppingList ..|> ShoppingListInterface

class ConcreteShoppingList #lightblue
ConcreteShoppingList "0..*" --|> "1" AbstractShoppingList
ConcreteShoppingList "1..*" .u.> "1" DataFlowController

class ConcreteRecipe #lightblue
ConcreteRecipe "0..*" --|> "1" AbstractRecipe
ConcreteRecipe "1..*" .u.> "1" DataFlowController

class RecipeIngredient #lightblue
RecipeIngredient "1..*" -u-* "1..*" ConcreteRecipe
RecipeIngredient -d-|> AbstractItem

class NonFoodItem #lightblue
NonFoodItem "0..*"-u-o "1..*" ConcreteShoppingList
NonFoodItem -d-|> AbstractItem

legend bottom left
| **Color**         | **Layer**             |
| <#lightgreen>     | Database layer        |
| <#lightblue>      | Application layer     |
| <#lightsalmon>    | Presentation layer    |
end legend
@enduml