@startuml
hide empty members


interface DatabaseAPI #lightgreen


interface GUI #lightsalmon
GUI ..> ApplicationAPI


interface ItemListInterface #lightblue

class ItemBuilder #lightblue{
    + addRecipeQuantity()
    + addRecipeUnit()
    + addQuantity()
    + build()
}
ItemBuilder ..> AbstractItem: <<create>>

abstract class AbstractItem #lightblue{
    - quantity
}

abstract class AbstractDatabaseAdapter #lightblue
AbstractDatabaseAdapter ..> DatabaseAPI

class ConcreteDatabaseAdapter #lightblue
ConcreteDatabaseAdapter --|> AbstractDatabaseAdapter

class DataStorageController #lightblue
DataStorageController "1" ..> "1..*" AbstractDatabaseAdapter

interface ApplicationAPI #lightblue
ApplicationAPI ..|> ItemListInterface

class ShoppingList #lightblue
ShoppingList "0..*" --|> "1" AbstractItemList

class Recipe #lightblue
Recipe "0..*" --|> "1" AbstractItemList

abstract class AbstractItemList #lightblue{
    + addItem()
    + removeItem()
    + storeList()
}
AbstractItemList ..> DataStorageController
AbstractItemList .l.> ItemListInterface

class RecipeIngredient #lightblue {
    - recipeQuantity
    - recipeUnit
}
RecipeIngredient "1..*" --o "1..*" Recipe
RecipeIngredient -u-|> AbstractItem

class NonFoodItem #lightblue
NonFoodItem "0..*"--o "1..*" ShoppingList
NonFoodItem -u-|> AbstractItem

legend bottom right
| **Color**         | **Layer**             |
| <#lightgreen>     | Database layer        |
| <#lightblue>      | Application layer     |
| <#lightsalmon>    | Presentation layer    |
end legend
@enduml