@startuml
hide empty members


interface DataBaseInterface #lightgreen

abstract class AbstractDatabase #lightgreen
AbstractDatabase -- DataBaseInterface

class ConcreteDatabase #lightgreen
ConcreteDatabase --|> AbstractDatabase

class DataAccessController #lightgreen
DataAccessController ..> Application
DataAccessController .u.> DataBaseInterface

interface GUI #lightsalmon
GUI .u.> Application

class Application #lightblue

@enduml