@startuml
hide empty members


class Database #lightgreen

abstract class AbstractRepository #lightgreen

class ConcreteRepository #lightgreen
ConcreteRepository --|> AbstractRepository
ConcreteRepository .u.> Database

interface Repository #lightgreen
Repository ..> ServiceLayer
Repository -l- AbstractRepository


interface GUI #lightsalmon
GUI .u.> ServiceLayer

interface ServiceLayer #plum

@enduml