@startuml
hide empty members


interface ItemListInterface #lightblue

class ItemListBuilder #lightblue{
    + addRecipeUnit()
    + addInstructions()
    + addDescription()
    + addDataBase()
    + build()
}
ItemListBuilder ..> Recipe: <<create>>
ItemListBuilder ..> ShoppingList: <<create>>

class ItemBuilder #lightblue{
   + addUnit()
   + addName()
   + build()
}
ItemBuilder ..> ConcreteItem: <<create>>

abstract class AbstractItem #lightblue{
   - unit
   - name
   + changeItem()
}
AbstractItem ..o AbstractItemList
AbstractItem -- Unit

class ItemListManager #lightblue
ItemListManager .u.> AbstractItemList
ItemListManager .u.> ItemListInterface

interface ApplicationAPI #lightblue
ApplicationAPI .r.> ItemListManager

class ShoppingList #lightblue
ShoppingList "0..*" --|> "1" AbstractItemList

class Recipe #lightblue {
    - instructions
    - description
    + getInstructions()
    + setInstructions()
    + getDescription()
    + setDescription()
}
Recipe "0..*" --|> "1" AbstractItemList

abstract class AbstractItemList #lightblue{
   - name
   - itemQuantity: [item: Quantity]
   - dataBaseName: str
   + addItem()
   + removeItem()
   + getItems()
   + storeList()
   + changeList()
}
AbstractItemList .l.> ItemListInterface
AbstractItemList -- Quantity

class ConcreteItem #lightblue
'NonFoodItem "0..*"--o "1..*" ShoppingList
ConcreteItem -u-|> AbstractItem

class Quantity #lightblue{
    - unit: Unit
    - quantity: int
    + getUnit()
    + getQuantity()
    + setQuantity()
}

class Unit #lightblue{
    - unit: str
    + getUnit()
}

legend bottom right
| **Color**         | **Layer**             |
| <#lightblue>      | Application layer     |
end legend
@enduml