@startuml

component Application #lightblue

database DataBase #lightgreen

component Repository
Repository .l.> Application: loads and saves state of
Repository ..> DataBase: commits changes to


component ServiceLayer #plum
ServiceLayer ..> Application: controls
ServiceLayer ..> Repository: controls


component GUI #lightsalmon
GUI ..> ServiceLayer
@enduml
