@startuml

component Application #lightblue


database DataBase #lightgreen


component Repository #khaki
Repository ..> DataBase: commits changes to


component ServiceLayer #plum
ServiceLayer ..> Application: controls
ServiceLayer ..> Repository: controls


interface API
API ..> ServiceLayer


component GUI #lightsalmon
GUI ..> API

legend bottom left
| **Color**         | **Layer**             |
| <#lightgreen>     | Database layer        |
| <#khaki>          | Repositories          |
| <#lightblue>      | Application layer     |
| <#plum>           | Service layer         |
end legend
@enduml
